[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.113.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.113.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.113.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.113.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "*"
  to = "https://morgan.pomeroy.me"
  force = true

[[redirects]]
  from = "/"
  to = "https://morgan.pomeroy.me"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://morgan.pomeroy.me"
  status = 301
  force = true

[[redirects]]
  from = "https://ahomeformo.com"
  to = "https://morgan.pomeroy.me"
  status = 301
  force = true
